package com.example.surfme;

import androidx.appcompat.app.AppCompatActivity;
import androidx.fragment.app.Fragment;
import androidx.fragment.app.FragmentManager;

import android.os.Bundle;
import android.view.View;
import android.widget.ArrayAdapter;
import android.widget.AutoCompleteTextView;
import android.widget.EditText;
import android.widget.Toast;

public class MainActivity extends AppCompatActivity {
    Fragment frag;
    EditText auto;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        auto = findViewById(R.id.auto);

//        String one[] = {"apple.com",
//                "www.google.com",
//                "microsoft.com",
//                "cloudflare.com",
////                www.blogger.com",
////                support.google.com",
////                play.google.com",
////                linkedin.com",
////                maps.google.com",
////                adobe.com",
////                docs.google.com",
////                wordpress.org",
////                en.wikipedia.org",
////                mozilla.org",
////                plus.google.com",
////                sites.google.com",
////                googleusercontent.com",
////                accounts.google.com",
////                europa.eu",
////                youtu.be",
////                vimeo.com",
////                drive.google.com",
////                cnn.com",
////                github.com",
////                es.wikipedia.org",
////                medium.com",
////                istockphoto.com",
////                facebook.com",
////                bp.blogspot.com",
////                bbc.co.uk",
////                amazon.com",
////                line.me",
////                vk.com",
////                paypal.com",
////                policies.google.com",
////                msn.com",
////                uol.com.br",
////                developers.google.com",
////                whatsapp.com",
////                fr.wikipedia.org",
////                pt.wikipedia.org",
////                opera.com",
////                who.int",
////        www.yahoo.com",
////        imdb.com",
////        w3.org",
////        reuters.com",
////        gstatic.com",
////        mail.google.com",
////        myspace.com",
////        hugedomains.com",
////        t.me",
////        news.yahoo.com",
////        dailymotion.com",
////        google.es",
////        nytimes.com",
////        mail.ru",
////        globo.com",
////        jimdofree.com",
////        dropbox.com",
////        google.co.jp",
////        google.co.uk",
////        forbes.com",
////        get.google.com",
////        google.com.br",
////        live.com",
////        bbc.com",
////        google.de",
////        news.google.com",
////        feedburner.com",
////        theguardian.com",
////        washingtonpost.com",
////        nih.gov",
////        slideshare.net",
////        wikimedia.org",
////        creativecommons.org",
////        webmd.com",
////        businessinsider.com",
////        it.wikipedia.org",
////        amazon.co.uk",
////        android.com",
////        picasaweb.google.com",
////        ig.com.br",
////        issuu.com",
////        wired.com",
////        mediafire.com",
////        terra.com.br",
////        wsj.com",
////        files.wordpress.com",
////        lefigaro.fr",
////        abcnews.go.com",
////        foxnews.com",
////        themeforest.net",
////        youronlinechoices.com",
////        google.ru",
////        tinyurl.com",
////        usatoday.com",
////        scribd.com",
////        elpais.com",
////        translate.google.com",
////        wikia.com",
////        dan.com",
////        telegram.me",
////        cpanel.com",
////        namecheap.com",
////        bing.com
////        ft.com
////        independent.co.uk
////        archive.org
////        de.wikipedia.org
////        plesk.com
////        www.gov.uk
////        dailymail.co.uk
////        mirror.co.uk
////        aol.com
////        cdc.gov
////        code.google.com
////        marketingplatform.google.com
////        google.it
////        gravatar.com
////        aliexpress.com
////        fandom.com
////        cpanel.net
////        huffingtonpost.com
////        myaccount.google.com
////        un.org
////        thesun.co.uk
////        networkadvertising.org
////        photos.google.com
////        hatena.ne.jp
////        samsung.com
////        pinterest.com
////        www.wix.com
////        bit.ly
////        telegraph.co.uk
////        amazon.de
////        steampowered.com
////        latimes.com
////        ok.ru
////        office.com
////        bloomberg.com
////        booking.com
////        harvard.edu
////        twitter.com
////        fb.com
////        goo.gl
////        books.google.com
////        nasa.gov
////        change.org
////        cnet.com
////        search.google.com
////        amazon.co.jp
////        tools.google.com
////        google.fr
////        ebay.com
////        abril.com.br
////        buydomains.com
////        rakuten.co.jp
////        time.com
////        id.wikipedia.org
////        draft.blogger.com
////        aboutads.info
////        bloglovin.com
////        urbandictionary.com
////        umich.edu
////        hm.com
////        my.yahoo.com
////        chicagotribune.com
////        addthis.com
////        nginx.org
////        google.nl
////        columbia.edu
////        detik.com
////        ibm.com
////        rapidshare.com
////        kickstarter.com
////        newsweek.com
////        ovh.net
////        npr.org
////        economist.com
////        scoop.it
////        sciencedirect.com
////        guardian.co.uk
////        netvibes.com
////        ria.ru
////        washington.edu
////        privacyshield.gov
////        gnu.org
////        ggpht.com
////        enable-javascript.com
////        pixabay.com
////        cbsnews.com
////        engadget.com
////        lemonde.fr
////        yahoo.co.jp
////        britannica.com
////        yandex.ru
////        buzzfeed.com
////        instructables.com
////        techcrunch.com
////        dw.com
////        imageshack.us
////        adssettings.google.com
////        nokia.com
////        groups.google.com
////        secureserver.net
////        ovh.com
////        hp.com
////        ietf.org
////        whitehouse.gov
////        amazon.es
////        oup.com
////        stackoverflow.com
////        wp.com
////        depositfiles.com
////        yelp.com
////        playstation.com
////        rt.com
////        amazon.fr
////        ted.com
////        list-manage.com
////        google.com.tw
////        finance.yahoo.com
////        m.wikipedia.org
////        search.yahoo.com
////        discord.gg
////        bandcamp.com
////        naver.jp
////        ipv4.google.com
////        walmart.com
////        over-blog-kiwi.com
////        researchgate.net
////        instagram.com
////        elmundo.es
////        nature.com
////        ign.com
////        abc.net.au
////        addtoany.com
////        cnbc.com
////        goo.ne.jp
////        yale.edu
////        quora.com
////        gizmodo.com
////        mysql.com
////        godaddy.com
////        000webhost.com
////        shutterstock.com
////        ru.wikipedia.org
////        hollywoodreporter.com
////        biglobe.ne.jp
////        abc.es
////        trustpilot.com
////        weibo.com
////        ytimg.com
////        akamaihd.net
////        nypost.com
////        mozilla.com
////        forms.gle
////        www.over-blog.com
////        ja.wikipedia.org
////        sendspace.com
////        gofundme.com
////        yadi.sk
////        cornell.edu
////        express.co.uk
////        unesco.org
////        news.com.au
////        nicovideo.jp
////        disqus.com
////        noaa.gov
////        theglobeandmail.com
////        loc.gov
////        php.net
////        t.co
////        metro.co.uk
////        bp2.blogger.com
////        storage.googleapis.com
////        netflix.com
////        google.co.in
////        mit.edu
////        bt.com
////        nikkei.com
////        digg.com
////        sapo.pt
////        picasa.google.com
////        cambridge.org
////        ea.com
////        ikea.com
////        nydailynews.com
////        vice.com
////        usnews.com
////        mega.nz
////        alibaba.com
////        arxiv.org
////        psychologytoday.com
////        deezer.com
////        afternic.com
////        bitly.com
////        pbs.org
////        princeton.edu
////        photobucket.com
////        sciencemag.org
////        soundcloud.com
////        google.pl
////        nvidia.com
////        blackberry.com
////        pl.wikipedia.org
////        ovh.co.uk
////        smh.com.au
////        4shared.com
////        skype.com
////        welt.de
////        apache.org
////        goodreads.com
////        eventbrite.com
////        worldbank.org
////        disney.com
////        nbcnews.com
////        theatlantic.com
////        theverge.com
////        wikihow.com
////        about.com
////        stanford.edu
////        rambler.ru
////        spiegel.de
////        tripadvisor.com
////        twitch.tv
////        mashable.com
////        google.ca
////        oracle.com
////        www.weebly.com
////        academia.edu
////        vox.com
////        ox.ac.uk
////        gmail.com
////        asus.com
////        surveymonkey.com
////        variety.com
////        sputniknews.com
////        standard.co.uk
////        thetimes.co.uk
////        nationalgeographic.com
////        channel4.com
////        sciencedaily.com
////        berkeley.edu
////        shopify.com
////        googleblog.com
////        www.wikipedia.org
////        newyorker.com
////        espn.com
////        box.com
////        sedo.com
////        ziddu.com
////        sfgate.com
////        wiley.com
////        icann.org
////        dell.com
////        e-recht24.de
////        doubleclick.net
////        xbox.com
////        target.com
////        naver.com
////        huffpost.com
////        spotify.com
////        wa.me
////        zendesk.com
////        google.co.id
////        cbc.ca
////        utexas.edu
////        indiatimes.com
////        nginx.com
////        udemy.com
////        sina.com.cn
////        ndtv.com
////        greenpeace.org
////        coursera.org
////        corriere.it
////        csmonitor.com
////        iubenda.com
////        searchenginejournal.com
////        behance.net
////        house.gov
////        dribbble.com
////        weforum.org
////        wiktionary.org
////        m.me
////        axs.com
////        airbnb.com
////        about.me
////        a8.net
////        viagens.com.br
////        steamcommunity.com
////        adweek.com
////        thedailybeast.com
////        amazon.it
////        thehill.com
////        snapchat.com
////        xing.com
////        offset.com
////        zdnet.com
////        orange.fr
////        e-monsite.com
////        ebay.co.uk
////        tabelog.com
////        answers.com
////        thefreedictionary.com
////        thestar.com
////        discovery.com
////        slate.com
////        oecd.org
////        answers.yahoo.com
////        dreniq.com
////        so-net.ne.jp
////        giphy.com
////        doi.org
////        medicalnewstoday.com
////        entrepreneur.com
////        cia.gov
////        ca.gov
////        consumerreports.org
////        pastebin.com
////        statista.com
////        arstechnica.com
////        rollingstone.com
////        imgur.com
////        politico.com
////        inc.com
////        zeit.de
////        20minutos.es
////        techradar.com
////        merriam-webster.com
////        fortune.com
////        bp1.blogger.com
////        asahi.com
////        businesswire.com
////        autodesk.com
////        pcmag.com
////        cmu.edu
////        groups.yahoo.com
////        brandbucket.com
////        calendar.google.com
////        vkontakte.ru
////        xinhuanet.com
////        www.livejournal.com
////        megaupload.com
////        sakura.ne.jp
////        ameblo.jp
////        geocities.com
////        fastcompany.com
////        www.canalblog.com
////        ucoz.ru
////        interia.pl
////        debian.org
////        usgs.gov
////        teamviewer.com
////        outlook.com
////        thenextweb.com
////        amazon.ca
////        billboard.com
////        thoughtco.com
////        gutenberg.org
////        disney.go.com
////        lycos.com
////        fb.me
////        archives.gov
////        irs.gov
////        fifa.com
////        epa.gov
////        iso.org
////        mail.yahoo.com
////        qq.com
////        allaboutcookies.org
////        springer.com
////        public-api.wordpress.com
////        sky.com
////        imageshack.com
////        prestashop.com
////        cbslocal.com
////        intel.com
////        prezi.com
////        indiegogo.com
////        marketwatch.com
////        mhlw.go.jp
////        stuff.co.nz
////        storage.canalblog.com
////        eff.org
////        soratemplates.com
////        home.neustar
////        evernote.com
////        reverbnation.com
////        marriott.com
////        histats.com
////        ap.org
////        amazon.in
////        illinois.edu",
////        allrecipes.com ",
////        repubblica.it",
////        biblegateway.com",
////        "ibtimes.com"
//};
//        ArrayAdapter array = new ArrayAdapter<String>(this, android.R.layout.simple_spinner_item,one) ;
//        array.setDropDownViewResource(android.R.layout.simple_spinner_item);
//        auto.setAdapter(array);

    }

    public void click(View view) {
        Toast.makeText(MainActivity.this, "You clicked a button",Toast.LENGTH_LONG).show();
    }

    @Override
    public void onBackPressed() {
        System.exit(0);
        super.onBackPressed();
    }

}